name: affine
description: Affine transformations calculations to get a mix of a transformation matrix and translation.
version: 0.1.0
repository: https://github.com/xclud/dart_affine

environment:
  sdk: ^2.12.0

# Add regular dependencies here.
dependencies:
  vector_math: ^2.1.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
